# Make this so it has the info about what this package does, and demos of each of the functions
```{r}
library(IEtools)
test1 <- c(4,3,2,6,5,10)
test2 <- rnorm(50, mean = 36, sd = 2)
```
```{r}
bb <- readr::read_csv(here::here("BananaBread.csv"), col_names = TRUE) 
colnames(bb) <- c("Pattern", "Treatment", "Value")
rownames(bb) <- seq_along(1:nrow(bb))

moth <- readr::read_csv(here::here("twan03.csv"), col_names = TRUE)
moth <- moth %>%
  pivot_longer(names_to = "Lure", values_to = "Count", cols = Scent:Chemical)
  

```

```{r}
stat_ci(bb$Value)

```
```{r}
stat_anova(bb, trtA = Treatment, value = Value)


```
```{r}
stat_anova(moth, trtA = Lure, trtB = Location, value = Count, twoway = TRUE)
```
```{r}
test_2way <- aov(Count ~ Lure * Location, data = moth)
# USe a plus instead of a star to remove interaction, 
# Just one factor will create a one way anova

summary(test_2way)
```


```{r}
#stat_ttest(bb, trt = Treatment, value = Value)
```
```{r}
obs <- readr::read_csv(here::here("dts_obs.csv"), col_names = TRUE) %>%
  select(-Element)
irreg <- readr::read_csv(here::here("dts_irreg.csv"), col_names = TRUE) %>%
  select(-Element)
```


```{r}
stnd_time(obs, irreg = irreg, allow = 0.09)
```
```{r}
WH_model <- matrix(c(c(1,1,1,1,1,0,0,0,0),
                     c(1,0,1,0,0,0,1,0,1),
                     c(0,1,0,1,1,1,0,1,0), 
                     c(0,0,0,0,1,1,1,1,1)), 
                   ncol = 4)


wh_cover(WH_model)

```
```{r}
wh_partition(WH_model)
```

```{r}
cash_flow(1000, i = .025, n = 24)
```
```{r}
flow <- c(-30000, 8000, 8000, 8000, 8000, 8000, 15000)

cash_viz(flow)
```


```{r}
ControlChart(bb, value = Value) 

```
```{r}
forecast = c(100, 120 ,140 , 104, 140, 140, 150, 100, 200)

produce_compare(forecast, method = "Flex", inv0 = 50)
```

